[general]
static=yes
writeprotect=no

[internal]

; For testing mic & speakers

exten => 6001,1,Answer()
same => n,Playback(demo-congrats)
same => n,Echo()
same => n,Hangup()

; FastAGI Balance Query -> Dialing 7000
exten => 7000,1,Answer()
exten => 7000,2,AGI(agi://127.0.0.1/balanceCheck)
exten => 7000,3,Hangup()
